In [1]:
!pip install openai langchain

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.5/83.5 kB 664.6 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.7/226.7 kB 1.2 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 816.1/816.1 kB 1.4 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 387.7/387.7 kB 1.9 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.1 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.1/242.1 kB 3.9 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.8/394.8 kB 3.9 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 3.6 MB/s et

In [42]:
# Import necessary libraries
from langchain.embeddings import FakeEmbeddings
import pandas as pd
#OPENAI_API_KEY = env_banake_usme_daal_bsdk
fake_embeddings = FakeEmbeddings(size=100)

cities_df = pd.read_csv("cities_r2.csv")

# Initialize an empty list to store embeddings
embeddings_list = []


# Initialize an empty list to store strings for each row
# row_strings = []

# Iterate over each row in the DataFrame
for index, row in cities_df.iterrows():
    # Initialize an empty string for the current row
    current_row_string = ""
    
    # Iterate over each value in the row
    for value in row:
        # Concatenate the value to the current row string
        current_row_string += str(value) + " "
    
    # Append the current row string to the list
    
    city_embedding = fake_embeddings.embed_query(current_row_string.strip())

    embeddings_list.append(city_embedding)
    # row_strings.append(current_row_string.strip())  # strip() removes trailing whitespace
    print(current_row_string)


Abohar  PUNJAB 145238 890 79.86 73.59 16287 
Achalpur  MAHARASHTRA 112293 928 91.99 89.0 8863 
Adilabad  ANDHRA PRADESH 117388 982 80.51 72.73 10565 
Adityapur  JHARKHAND 173988 902 83.46 76.23 19225 
Adoni  ANDHRA PRADESH 166537 1013 68.38 60.33 11902 
Agartala  TRIPURA 399688 1002 93.88 92.02 52711 
Agra  UTTAR PRADESH 1574542 853 63.44 58.54 185813 
Ahmadabad  GUJARAT 5570585 897 89.62 84.81 769858 
Ahmadnagar  MAHARASHTRA 350905 952 91.49 87.33 51661 
Aizawl  MIZORAM 291822 1029 98.8 98.31 26832 
Ajmer  RAJASTHAN 542580 946 87.53 81.53 77989 
Akbarpur  UTTAR PRADESH 111594 939 76.94 69.54 9745 
Akola  MAHARASHTRA 427146 958 91.34 87.77 49715 
Alandur  TAMIL NADU 164162 997 95.15 93.1 45971 
Alappuzha  KERALA 174164 1076 96.56 95.21 22263 
Aligarh  UTTAR PRADESH 872575 884 70.36 64.55 99341 
Allahabad  UTTAR PRADESH 1117094 858 86.5 82.17 233129 
Alwar  RAJASTHAN 315310 889 86.78 79.05 58764 
Ambala  HARYANA 196216 895 88.23 84.51 34943 
Ambala Sadar  HARYANA 104268 922 87.97 87.22 

In [44]:
# Assuming you've imported necessary libraries
import pandas as pd

# Read the CSV file into a DataFrame
cities_df = pd.read_csv("cities_r2.csv")

# Initialize an empty list to store strings for each row
# row_strings = []

# Iterate over each row in the DataFrame
for index, row in cities_df.iterrows():
    # Initialize an empty string for the current row
    current_row_string = ""
    
    # Iterate over each value in the row
    for value in row:
        # Concatenate the value to the current row string
        current_row_string += str(value) + " "
    
    # Append the current row string to the list
    
    city_embedding = fake_embeddings.embed_query(current_row_string.strip())

    embeddings_list.append(city_embedding)
    # row_strings.append(current_row_string.strip())  # strip() removes trailing whitespace
    print(current_row_string,embeddings_list[0])

# Now, row_strings contains a string representation for each row in the DataFrame


Abohar  PUNJAB 145238 890 79.86 73.59 16287  [0.034410701548468745, 0.21458582240129337, -1.2960948918234463, -0.5148839389628852, -0.24474202396118733, -0.2538626108008693, -0.037547806652882904, 0.5602757045037703, -1.5857328287535353, 0.39819775427419746, -0.8388380379340575, -0.9837261463069216, -0.1970206273779794, -0.29676043498042365, -0.6204593107097408, 0.7925929330405187, -0.6663270744409102, 0.658088311362311, 0.5440103275546165, -0.1302929653033749, -0.4530101196196035, -2.4155877464517803, -2.259355191752668, 0.3708726224082541, -1.5184948570444496, 0.3779874961486139, 0.956096197705598, -0.006533714208263191, 0.5482768877694003, 1.379750178109731, -0.8908950560175793, 0.6762202509551325, 1.5323064363877072, -1.1448128074552122, -1.0133255763768316, -0.4651456950317854, 0.1781714411676514, 0.021982711862842206, 0.43220197156271284, 0.4280117533378517, 0.8360692101853401, -0.6982713595788782, -0.04972098870327558, -0.6793834083089623, -0.9106797896568272, -1.016998690681650

In [45]:
import numpy as np

embeddings_list = np.array(embeddings_list).astype("float32")
embeddings_list[0]

array([ 0.0344107 ,  0.21458583, -1.2960949 , -0.51488394, -0.24474202,
       -0.25386262, -0.03754781,  0.56027573, -1.5857328 ,  0.39819774,
       -0.83883804, -0.98372614, -0.19702062, -0.29676044, -0.6204593 ,
        0.79259294, -0.66632706,  0.6580883 ,  0.54401034, -0.13029297,
       -0.4530101 , -2.4155877 , -2.2593553 ,  0.37087262, -1.5184948 ,
        0.3779875 ,  0.9560962 , -0.00653371,  0.5482769 ,  1.3797501 ,
       -0.89089507,  0.67622024,  1.5323064 , -1.1448128 , -1.0133256 ,
       -0.4651457 ,  0.17817144,  0.02198271,  0.43220198,  0.42801175,
        0.8360692 , -0.69827133, -0.04972099, -0.6793834 , -0.9106798 ,
       -1.0169986 ,  0.3588543 ,  1.1938782 , -0.5975143 ,  0.10627436,
        0.8308705 , -1.0690439 , -0.48127162, -0.42114154, -0.11558081,
        0.01883973,  0.99006265, -1.0529459 ,  1.9093037 ,  0.00879529,
       -0.45346215,  1.8929034 ,  1.2244507 , -0.79099566, -0.1283098 ,
        0.6272477 , -0.54783076, -0.1541266 ,  1.3840166 ,  2.03

In [46]:
!pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 655.0 kB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [47]:
import faiss as f

In [49]:
index = f.IndexFlatL2(fake_embeddings.size)
index.add(embeddings_list)

In [50]:
testing = "alwar rajasthan 1000000 80.0 "
test = fake_embeddings.embed_query(testing)
test = np.array(([test])).astype("float32")

In [ ]:
test

array([[-0.24439293, -2.1172278 ,  0.26613638, -1.1138947 ,  1.1733003 ,
         0.3064965 ,  0.7817026 , -0.45730802,  0.37570143, -0.67781293,
        -1.2924465 , -0.7261879 , -0.10750856, -0.01901701, -0.76043063,
         0.9681475 , -0.30870497,  0.10289641, -1.9145064 , -1.9025955 ,
         0.7465854 ,  1.2623192 ,  0.16444165,  0.46157125,  0.1091281 ,
         0.75749904, -0.40099758, -1.3610657 ,  2.5613506 ,  0.1455003 ,
        -0.7071946 ,  1.2999396 , -0.10148025, -0.880892  , -1.037733  ,
         1.2387319 ,  0.87802786, -1.501443  , -0.7083844 , -0.4712949 ,
        -0.90670043,  0.6483189 ,  0.5678092 ,  0.0875416 ,  0.16264054,
        -0.8174038 ,  0.08566021, -0.7057797 ,  0.1976268 ,  0.98075587,
        -1.8581104 , -0.14726974,  2.6504025 ,  0.30750784, -0.15929088,
        -0.30213407,  0.36967757, -1.1648531 , -0.42448613,  0.73032516,
         0.21969634, -0.85209584,  1.065194  ,  0.5727243 ,  0.5480814 ,
        -0.35792264,  0.91019905, -0.2930588 , -0.8

In [51]:
k = 10
dist, indices = index.search(test, 10)

In [52]:
indices

array([[ 791,  270,  222,  317,  762, 1334, 1243, 1245,  375,   74]])

In [ ]:
cities_df[175]

KeyError: 175